# Generated by Django 4.2.23 on 2025-06-16 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_ingredient_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='date_added',
        ),
    ]
