# Generated by Django 4.2.23 on 2025-06-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ingredients', models.TextField(help_text='Enter the ingredients, separated by a comma')),
                ('cooking_time', models.PositiveIntegerField(help_text='Enter cooking time in minutes')),
            ],
        ),
    ]
