# Generated by Django 4.2.23 on 2025-06-16 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_recipeingredient_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='date_added',
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes_recipe_ingredients', to='recipes.recipe'),
        ),
    ]
