# Generated by Django 4.2.23 on 2025-06-16 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_remove_ingredient_date_added_and_more'),
        ('recipeingredients', '0002_recipeingredient_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='date_added',
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipeingredients_recipe_ingredients', to='recipes.recipe'),
        ),
    ]
